---
- name: Simple Test Playbook
  hosts: db_hosts, dev_hosts
  gather_facts: false

  tasks:
    - name: Task1 Ping the remote host
      ansible.builtin.ping:
      
    - name: Task2 Copy file hosts with permissions
      ansible.builtin.copy:
        src: ./files
        dest: /home/apap/Desktop
        mode: '0644'

