# Example: Core-Banking Exp1
---
- name: My first Play
  hosts: core_banking
  become: yes
  vars:
    app_user: corebank
    packages_to_install:
      - nano
      - curl

  tasks:

    - name: Check SSH connectivity
      ansible.builtin.ping:
      tags: [connectivity]

    - name: Create application user
      ansible.builtin.user:
        name: "{{ app_user }}"
        shell: /bin/bash
        state: present
      tags: [users]

    - name: Install essential packages (only on app servers)
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_install }}"
      when: "'core_banking_app' in group_names"
      tags: [packages]